/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BeginnerPortalRouteImport } from './routes/beginner-portal'
import { Route as AccuracyRouteImport } from './routes/accuracy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StocksIndexRouteImport } from './routes/stocks.index'
import { Route as StocksSymbolRouteImport } from './routes/stocks.$symbol'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BeginnerPortalRoute = BeginnerPortalRouteImport.update({
  id: '/beginner-portal',
  path: '/beginner-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccuracyRoute = AccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksIndexRoute = StocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StocksRoute,
} as any)
const StocksSymbolRoute = StocksSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => StocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/beginner-portal': typeof BeginnerPortalRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/stocks': typeof StocksRouteWithChildren
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks/': typeof StocksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/beginner-portal': typeof BeginnerPortalRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks': typeof StocksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accuracy': typeof AccuracyRoute
  '/beginner-portal': typeof BeginnerPortalRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/portfolio': typeof PortfolioRoute
  '/stocks': typeof StocksRouteWithChildren
  '/stocks/$symbol': typeof StocksSymbolRoute
  '/stocks/': typeof StocksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accuracy'
    | '/beginner-portal'
    | '/compare'
    | '/dashboard'
    | '/portfolio'
    | '/stocks'
    | '/stocks/$symbol'
    | '/stocks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accuracy'
    | '/beginner-portal'
    | '/compare'
    | '/dashboard'
    | '/portfolio'
    | '/stocks/$symbol'
    | '/stocks'
  id:
    | '__root__'
    | '/'
    | '/accuracy'
    | '/beginner-portal'
    | '/compare'
    | '/dashboard'
    | '/portfolio'
    | '/stocks'
    | '/stocks/$symbol'
    | '/stocks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccuracyRoute: typeof AccuracyRoute
  BeginnerPortalRoute: typeof BeginnerPortalRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  PortfolioRoute: typeof PortfolioRoute
  StocksRoute: typeof StocksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beginner-portal': {
      id: '/beginner-portal'
      path: '/beginner-portal'
      fullPath: '/beginner-portal'
      preLoaderRoute: typeof BeginnerPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accuracy': {
      id: '/accuracy'
      path: '/accuracy'
      fullPath: '/accuracy'
      preLoaderRoute: typeof AccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/': {
      id: '/stocks/'
      path: '/'
      fullPath: '/stocks/'
      preLoaderRoute: typeof StocksIndexRouteImport
      parentRoute: typeof StocksRoute
    }
    '/stocks/$symbol': {
      id: '/stocks/$symbol'
      path: '/$symbol'
      fullPath: '/stocks/$symbol'
      preLoaderRoute: typeof StocksSymbolRouteImport
      parentRoute: typeof StocksRoute
    }
  }
}

interface StocksRouteChildren {
  StocksSymbolRoute: typeof StocksSymbolRoute
  StocksIndexRoute: typeof StocksIndexRoute
}

const StocksRouteChildren: StocksRouteChildren = {
  StocksSymbolRoute: StocksSymbolRoute,
  StocksIndexRoute: StocksIndexRoute,
}

const StocksRouteWithChildren =
  StocksRoute._addFileChildren(StocksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccuracyRoute: AccuracyRoute,
  BeginnerPortalRoute: BeginnerPortalRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  PortfolioRoute: PortfolioRoute,
  StocksRoute: StocksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
